name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Release, Debug] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Configure CMake
        run: cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -Dbuild_tests=ON

      - name: Build tests
        run: cmake --build build --parallel

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

      - name: Verify header-only install
        run: |
          mkdir install_test
          cd install_test
          cmake -S .. -B build_install_test \
            -DCMAKE_PREFIX_PATH="${{ github.workspace }}/build" \
            -Dbuild_tests=OFF
          cmake --build build_install_test
